//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraduationDesign_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTable
    {
        public int Id { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public string SessionKey { get; set; }
        public int UploadId { get; set; }
        public int DownloadId { get; set; }
    }
}
